In [1]:
#importation des librairies
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import seaborn as sns

#charder le fichier csv
data_std = pd.read_csv("/home/abdoulaye/Documents/Orange Digital center/projets/projet_data/data/ai_student_impact_dataset.csv")
data_std.head(10)

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
5,100006,STEM,Junior,3.449,6.50,Debugging/Troubleshooting,Beginner,1,False,14.19,4,Allowed_With_Citation,5,3.666,65.92,High
6,100007,STEM,Freshman,3.622,31.41,Summarizing_Reading,Advanced,5,True,13.11,8,Allowed_With_Citation,7,4.000,67.97,Medium
7,100008,Arts,Junior,2.746,5.33,Copywriting/Drafting,Intermediate,3,False,18.45,2,Actively_Encouraged,1,2.965,85.09,Medium
8,100009,Business,Sophomore,3.420,2.00,Debugging/Troubleshooting,Beginner,2,True,2.87,1,Strict_Ban,5,3.396,55.71,Medium
9,100010,Business,Sophomore,3.046,19.99,Debugging/Troubleshooting,Intermediate,2,True,12.49,3,Strict_Ban,8,2.978,87.18,High

In [ ]:
# Calcule la moyenne uniquement pour les colonnes contenant des nombres
moyenne = data_std.mean(numeric_only=True)
print(moyenne)

Student_ID                    125000.500000
Pre_Semester_GPA                   3.146102
Weekly_GenAI_Hours                 8.427752
Tool_Diversity                     2.800260
Paid_Subscription                  0.423080
Traditional_Study_Hours           11.209271
Perceived_AI_Dependency            3.505360
Anxiety_Level_During_Exams         4.270760
Post_Semester_GPA                  3.349299
Skill_Retention_Score             75.798125
dtype: float64

In [ ]:
# Calcule la mediane uniquement pour les colonnes contenant des nombres
mediane = data_std.median(numeric_only=True)
print(mediane)

Student_ID                    125000.500
Pre_Semester_GPA                   3.210
Weekly_GenAI_Hours                 5.800
Tool_Diversity                     3.000
Paid_Subscription                  0.000
Traditional_Study_Hours           11.180
Perceived_AI_Dependency            3.000
Anxiety_Level_During_Exams         4.000
Post_Semester_GPA                  3.421
Skill_Retention_Score             76.000
dtype: float64

In [ ]:
# Calcule le minimum uniquement pour les colonnes contenant des nombres
minimum = data_std.min(numeric_only=True)
print(minimum)

Student_ID                    100001
Pre_Semester_GPA               1.183
Weekly_GenAI_Hours               0.0
Tool_Diversity                     1
Paid_Subscription              False
Traditional_Study_Hours          1.0
Perceived_AI_Dependency            1
Anxiety_Level_During_Exams         1
Post_Semester_GPA                1.0
Skill_Retention_Score          10.78
dtype: object

In [ ]:
# Calcule le maximum uniquement pour les colonnes contenant des nombres
maximum = data_std.max(numeric_only=True)
print(maximum)

Student_ID                    150000
Pre_Semester_GPA               3.998
Weekly_GenAI_Hours              40.0
Tool_Diversity                     5
Paid_Subscription               True
Traditional_Study_Hours        35.86
Perceived_AI_Dependency           10
Anxiety_Level_During_Exams        10
Post_Semester_GPA                4.0
Skill_Retention_Score          100.0
dtype: object

In [ ]:
# Calcule la variance uniquement pour les colonnes contenant des nombres
variance = data_std.var(numeric_only=True)
print(variance)

Student_ID                    2.083375e+08
Pre_Semester_GPA              2.293015e-01
Weekly_GenAI_Hours            6.838446e+01
Tool_Diversity                1.411392e+00
Paid_Subscription             2.440882e-01
Traditional_Study_Hours       2.658873e+01
Perceived_AI_Dependency       3.315358e+00
Anxiety_Level_During_Exams    4.597021e+00
Post_Semester_GPA             2.456913e-01
Skill_Retention_Score         1.764016e+02
dtype: float64

In [ ]:
# Calcule l'ecart type uniquement pour les colonnes contenant des nombres
ecart_type = data_std.std(numeric_only=True)
print(ecart_type)

Student_ID                    14433.901067
Pre_Semester_GPA                  0.478854
Weekly_GenAI_Hours                8.269490
Tool_Diversity                    1.188020
Paid_Subscription                 0.494053
Traditional_Study_Hours           5.156426
Perceived_AI_Dependency           1.820812
Anxiety_Level_During_Exams        2.144066
Post_Semester_GPA                 0.495673
Skill_Retention_Score            13.281626
dtype: float64

In [3]:
# on isole colonne avec les nombres
df_num = data_std.select_dtypes(include='number')

# Calcule les quartilles et percentilles uniquement pour les colonnes contenant des nombres
quartiles_df = df_num.quantile([0.10, 0.25, 0.50, 0.75, 0.90])
display(quartiles_df)

,Student_ID,Pre_Semester_GPA,Weekly_GenAI_Hours,Tool_Diversity,Traditional_Study_Hours,Perceived_AI_Dependency,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score
0.10,105000.90,2.471,0.87,1.0,4.36,1.0,1.0,2.65200,58.550
0.25,112500.75,2.834,2.39,2.0,7.56,2.0,3.0,3.02375,66.820
0.50,125000.50,3.210,5.80,3.0,11.18,3.0,4.0,3.42100,76.000
0.75,137500.25,3.521,11.72,4.0,14.71,5.0,6.0,3.74900,85.190
0.90,145000.10,3.724,20.02,5.0,17.92,6.0,7.0,3.99100,93.731

In [ ]:
# Calcul de l'IQR
iqr = (df_num.quantile(0.75) - df_num.quantile(0.25) )
print(iqr)

Student_ID                    24999.50000
Pre_Semester_GPA                  0.68700
Weekly_GenAI_Hours                9.33000
Tool_Diversity                    2.00000
Traditional_Study_Hours           7.15000
Perceived_AI_Dependency           3.00000
Anxiety_Level_During_Exams        3.00000
Post_Semester_GPA                 0.72525
Skill_Retention_Score            18.37000
dtype: float64

In [34]:
# === ANALYSE COMPLETE : Weekly_GenAI_Hours ===

# Q1, Q2, Q3
Q1 = data_std["Weekly_GenAI_Hours"].quantile(0.25)
Q2 = data_std["Weekly_GenAI_Hours"].quantile(0.50)
Q3 = data_std["Weekly_GenAI_Hours"].quantile(0.75)

# Statistiques de base
moyenne = data_std["Weekly_GenAI_Hours"].mean()
mediane = data_std["Weekly_GenAI_Hours"].median()
ecart_type = data_std["Weekly_GenAI_Hours"].std()
variance = data_std["Weekly_GenAI_Hours"].var()

# Coefficient de variation
cv = (ecart_type / moyenne) * 100

# IQR
iqr = Q3 - Q1

# Bornes outliers
limite_basse = Q1 - (1.5 * iqr)
limite_haute = Q3 + (1.5 * iqr)

# Détection outliers
outliers = data_std[data_std["Weekly_GenAI_Hours"] > limite_haute]
pourcentage_outliers = (len(outliers) / len(data_std)) * 100

# Affichage
print(" === ANALYSE COMPLETE : Weekly_GenAI_Hours ===")
print(f"Moyenne     : {moyenne:.2f}h")
print(f"Médiane     : {mediane:.2f}h")
print(f"Écart-type  : {ecart_type:.2f}h")
print(f"CV          : {cv:.2f}%")
print(f"Q1={Q1:.2f} | Q2={Q2:.2f} | Q3={Q3:.2f} | IQR={iqr:.2f}")
print(f"Borne haute : {limite_haute:.2f}h")
print(f"Outliers    : {len(outliers)} étudiants ({pourcentage_outliers:.2f}%)")

 === ANALYSE COMPLETE : Weekly_GenAI_Hours ===
Moyenne     : 8.43h
Médiane     : 5.80h
Écart-type  : 8.27h
CV          : 98.12%
Q1=2.39 | Q2=5.80 | Q3=11.72 | IQR=9.33
Borne haute : 25.72h
Outliers    : 2583 étudiants (5.17%)

In [5]:
# ===ANALYSE DE : Skill_Retention_Score======

#Q1, Q2, Q3
Q1_skill = data_std["Skill_Retention_Score"].quantile(0.25)
Q2_skill = data_std["Skill_Retention_Score"].quantile(0.50)
Q3_skill = data_std["Skill_Retention_Score"].quantile(0.75)

# les statistiques
moyenne_skill = data_std["Skill_Retention_Score"].mean()
mediane_skill = data_std["Skill_Retention_Score"].median()
ecart_type_skill = data_std["Skill_Retention_Score"].std()
variance_skill = data_std["Skill_Retention_Score"].var()

# coef de variantion
cv_skill = (ecart_type_skill / moyenne_skill) * 100

# IQR
iqr_skill = Q3_skill - Q1_skill

# calcules des outliers
borne_basse_skill = Q1_skill - (1.5 * iqr_skill)
borne_haute_skill = Q3_skill + (1.5 * iqr_skill)

# nbre ligne de outlier et %
outliers_skill1 = data_std[data_std["Skill_Retention_Score"] < borne_basse_skill]
pourcentage_outliers_skill1 = (len(outliers_skill1) / len(data_std) ) * 100

outliers_skill2 = data_std[data_std["Skill_Retention_Score"] > borne_haute_skill]
pourcentage_outliers_skill2 = (len(outliers_skill2) / len(data_std)) * 100

# Affichage
print(" === ANALYSE COMPLETE : Skill_Retention_Score ===")
print(f"Moyenne     : {moyenne_skill:.2f}")
print(f"Médiane     : {mediane_skill:.2f}")
print(f"Écart-type  : {ecart_type_skill:.2f}")
print(f"CV          : {cv_skill:.2f}%")
print(f"Q1={Q1_skill:.2f} | Q2={Q2_skill:.2f} | Q3={Q3_skill:.2f} | IQR={iqr_skill:.2f}")
print(f"Borne basse : {borne_basse_skill:.2f}")
print(f"Borne haute : {borne_haute_skill:.2f}")
print(f"Outliers    : {len(outliers_skill1)} étudiants ({pourcentage_outliers_skill1:.2f}%)")
print(f"Outliers    : {len(outliers_skill2)} étudiants ({pourcentage_outliers_skill2:.2f}%)")

 === ANALYSE COMPLETE : Skill_Retention_Score ===
Moyenne     : 75.80
Médiane     : 76.00
Écart-type  : 13.28
CV          : 17.52%
Q1=66.82 | Q2=76.00 | Q3=85.19 | IQR=18.37
Borne basse : 39.26
Borne haute : 112.75
Outliers    : 216 étudiants (0.43%)
Outliers    : 0 étudiants (0.00%)

In [ ]:
# ===ANALYSE DE : Anxiety_Level_During_Exams======

#Q1, Q2, Q3
Q1_anxiety = data_std["Anxiety_Level_During_Exams"].quantile(0.25)
Q2_anxiety = data_std["Anxiety_Level_During_Exams"].quantile(0.50)
Q3_anxiety = data_std["Anxiety_Level_During_Exams"].quantile(0.75)

# les statistiques
moyenne_anxiety = data_std["Anxiety_Level_During_Exams"].mean()
mediane_anxiety = data_std["Anxiety_Level_During_Exams"].median()
ecart_type_anxiety = data_std["Anxiety_Level_During_Exams"].std()
variance_anxiety = data_std["Anxiety_Level_During_Exams"].var()

# coef de variantion
cv_anxiety = (ecart_type_anxiety / moyenne_anxiety) * 100

# IQR
iqr_anxiety = Q3_anxiety - Q1_anxiety

# calcules des outliers
borne_basse_anxiety = Q1_anxiety - (1.5 * iqr_anxiety)
borne_haute_anxiety = Q3_anxiety + (1.5 * iqr_anxiety)

# nbre ligne de outlier et %
outliers_anxiety1 = data_std[data_std["Anxiety_Level_During_Exams"] < borne_basse_anxiety]
pourcentage_outliers_anxiety1 = (len(outliers_anxiety1) / len(data_std) ) * 100

outliers_anxiety2 = data_std[data_std["Anxiety_Level_During_Exams"] > borne_haute_anxiety]
pourcentage_outliers_anxiety2 = (len(outliers_anxiety2) / len(data_std)) * 100

# Affichage
print(" === ANALYSE COMPLETE : Anxiety_Level_During_Exams ===")
print(f"Moyenne     : {moyenne_anxiety:.2f}")
print(f"Médiane     : {mediane_anxiety:.2f}")
print(f"Écart-type  : {ecart_type_anxiety:.2f}")
print(f"CV          : {cv_anxiety:.2f}%")
print(f"Q1={Q1_anxiety:.2f} | Q2={Q2_anxiety:.2f} | Q3={Q3_anxiety:.2f} | IQR={iqr_anxiety:.2f}")
print(f"Borne basse : {borne_basse_anxiety:.2f}")
print(f"Borne haute : {borne_haute_anxiety:.2f}")
print(f"Outliers    : {len(outliers_anxiety1)} étudiants ({pourcentage_outliers_anxiety1:.2f}%)")
print(f"Outliers    : {len(outliers_anxiety2)} étudiants ({pourcentage_outliers_anxiety2:.2f}%)")

 === ANALYSE COMPLETE : Anxiety_Level_During_Exams ===
Moyenne     : 4.27
Médiane     : 4.00
Écart-type  : 2.14
CV          : 50.20%
Q1=3.00 | Q2=4.00 | Q3=6.00 | IQR=3.00
Borne basse : -1.50
Borne haute : 10.50
Outliers    : 0 étudiants (0.00%)
Outliers    : 0 étudiants (0.00%)